on: pull_request
name: ShellCheck
jobs:
  shellcheck:
    runs-on: debian-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        args: wireguard-server.sh
