on: push
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        args: wireguard-server.sh -e C2034,SC2162,SC2140,SC2027,SC2086,SC2140,SC1117
